package net.judah.plugin;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum ModhostError {

	SUCCESS(0), 
	
	INSTANCE_INVALID(-1), 
	INSTANCE_ALREADY_EXISTS(-2),  
	INSTANCE_NON_EXISTS(-3), 
	INSTANCE_UNLICENSED(-4), 
	LV2_INVALID_URI(-101), 
	LV2_INSTANTIATION(-102), 
	LV2_INVALID_PARAM_SYMBOL(-103), 
	LV2_INVALID_PRESET_URI(-104), 
	LV2_CANT_LOAD_STATE(-105), 
	JACK_CLIENT_CREATION(-201), 
	JACK_CLIENT_ACTIVATION(-202), 
	JACK_CLIENT_DEACTIVATION(-203), 
	JACK_PORT_REGISTER(-204), 
	JACK_PORT_CONNECTION(-205), 
	JACK_PORT_DISCONNECTION(-206), 
	ASSIGNMENT_ALREADY_EXISTS(-301), 
	ASSIGNMENT_INVALID_OP(-302), 
	ASSIGNMENT_LIST_FULL(-303), 
	ASSIGNMENT_FAILED(-304), 
	CONTROL_CHAIN_UNAVAILABLE(-401), 
	LINK_UNAVAILABLE(-402), 
	MEMORY_ALLOCATION(-901), 
	INVALID_OPERATION(-902);
	
	@Getter private final int code;
	


	
	
}
